services:
  db:
    container_name: dhbrews_db
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brews
    healthcheck:
      test: ['CMD', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
